### ISSUE TITLE
optional timeout

### ISSUE THREAD

**Issue by stropho** [drpicox/spy-middleware#1]
Hi, 
first of all: good job! The spy-middleware is what I was looking for.

Problem:
In case my test fail and the action I'm waiting for is not dispatched, there is no way how to handle that in the test. As a result the test runner/framework will fail with its own timeout.
Idea for enhancement:
Add option for timeout specifying when the promise gets rejected.
I'm not sure if it should be set in `makeSpyMiddleware(...)` or with each call, e.g. `spyMiddleware.untilNext()`, or both :)

I hope it is something that is considered potentially useful for this project. If there is a need for PR, let me know.

**Comment by drpicox** [comment]
I gave a lot of though about it when I did the last release, and I delayed it because there is a Trick,

```javascript
setTimeout(() => store.dispatch({ type: 'TIMEOUT' }), 1000)
await spyMiddleware.untilNext(/YOUR_TYPE|TIMEOUT/)
``` 

or with `const delay = (x) => new Promise((r) => setTimeout(r, x));`:

```javascript
Promise.race([
   delay(1000),
   await spyMiddleware.untilNext('YOUR_TYPE')
]);
```

But it may be unnecessary:

- as you comment framework fails if await does not finishes in few seconds, so the case of forgetting dispatch an action is working

- but it is difficult to test "this action will be not dispatched". ¿How many time is will be not dispatched? It is difficult to know that something will not happen ever. 
  It really looks like the [Halting Problem](https://en.wikipedia.org/wiki/Halting_problem).


May be you want to do something like:

```javascript
await someConditionReached;
expect(spyMiddleware.getAction('YOUR_TYPE')).toBeUndefined();
```

?

**Comment by stropho** [comment]
yes `Promise.race` crossed my mind, so here I thought, something like that could be implemented in the spy-middleware.
In a testing environment, I would expect that all async actions are fast  - let's say a tick. But I understand that providing timeout mechanism might result in using spy-middleware incorrectly for some test cases, especially for new-comers.

The main reason for me is that I wanted to write a custom error message in case the expected action is not dispatched. - that is write the error before the test framework crashes. But I can live without it :) Or use the mechanisms/tricks as you suggested.

Well thanks for the quick answer.

**Comment by drpicox** [comment]
You're welcome. 
No only for newcomers, also for me, just to think twice before test some things in some ways :D
